version: '3'
services:
  petclinic:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-2.c7mauago0hqg.us-east-1.rds.amazonaws.com:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=admin123
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=postgres"
